radiusnasid hs-b
dhcpif vethb
net 10.2.0.0/24
uamlisten 10.2.0.1
radiusserver1 127.0.0.1
radiussecret test
uamserver http://127.0.0.1/login
uamsecret test
cmdsocket /var/run/chilli.sock
pidfile /var/run/chilli.pid
