name: Github Actions Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install build deps
      run: |
        sudo apt update
        sudo apt install gengetopt libjson-c-dev
    - name: Bootstrap
      run: ./bootstrap
    - name: Configure
      run: |
        ./configure --prefix=/var/tmp/coova --with-openssl --with-nfcoova
    - name: Build
      run: make
    - name: Install
      run: make install
